prgrms-be-devcourse/NBE2-3-2-team9

src/main/java/com/team9/anicare/community/controller/CommunityController.java, src/main/java/com/team9/anicare/community/dto/CommunityRequestDTO.java, src/main/java/com/team9/anicare/community/dto/CommunityResponseDTO.java, src/main/java/com/team9/anicare/community/model/Community.java, src/main/java/com/team9/anicare/community/repository/CommunityRepository.java, src/main/java/com/team9/anicare/community/service/CommunityService.java, src/main/java/com/team9/anicare/user/model/User.java, src/main/java/com/team9/anicare/user/repository/UserRepository.java
=> feat : 게시글 조회, 생성, 수정, 삭제

src/main/java/com/team9/anicare/common/ResultCode.java, src/main/java/com/team9/anicare/pet/controller/PetController.java, src/main/java/com/team9/anicare/pet/model/Pet.java, src/main/java/com/team9/anicare/pet/repository/PetRepository.java, src/main/java/com/team9/anicare/schedule/controller/ScheduleController.java, src/main/java/com/team9/anicare/schedule/dto/ScheduleDTO.java, src/main/java/com/team9/anicare/schedule/model/Schedule.java, src/main/java/com/team9/anicare/schedule/repository/ScheduleRepository.java, src/main/java/com/team9/anicare/schedule/service/ScheduleService.java
=> feat : 비정기 스케줄 생성 수정 추가 삭제 구현

src/main/java/com/team9/anicare/auth/controller/AuthController.java, src/main/java/com/team9/anicare/auth/service/KakaoService.java, src/main/java/com/team9/anicare/user/controller/UserController.java
응답통일에서 String이 에러발생해서 수정했습니다 
아직 String은 응답통일이 되어있지않고 String 형태로 반환 추후 개선 예정
- ResponseEntity -> String
=> fix응답 타입 문제 해결 (ResponseEntity → String) 추후 String 형태 조정예정

src/main/java/com/team9/anicare/auth/config/SecurityConfig.java
프론트엔드와 연결을 위해 cors 설정을 해줬습니다.
- 변경사항 1
- 변경사항 2
- 변경사항 3
=> feat: 프론트엔드 cors 설정

src/main/java/com/team9/anicare/community/controller/CommentController.java, src/main/java/com/team9/anicare/community/controller/CommunityController.java
로그인된 유저 확인
@AuthenticationPrincipal로 userId 설정
=> refactor: 로그인된 유저 확인

src/main/java/com/team9/anicare/pet/service/PetService.java, src/main/java/com/team9/anicare/schedule/service/PeriodicScheduleService.java, src/main/java/com/team9/anicare/schedule/service/SingleScheduleService.java
jpaRepository.save랑 매퍼 관련해서 문제가 있었던 것 같은데 근본적인 해결은 못할 것 같고 임시방편으로 버그 수정 해봤습니다
=> fix : PUT 요청에 createAt,updateAt 안나오는 버그 수정

src/main/java/com/team9/anicare/community/controller/CommentController.java, src/main/java/com/team9/anicare/community/controller/CommunityController.java
유저의 권한 필요한 API에 권한 확인 코드 추가했습니다
- @PreAuthorized 설정
=> refactor: 사용자 권한 확인

src/main/java/com/team9/anicare/community/dto/CommentResponseDTO.java, src/main/java/com/team9/anicare/community/dto/CommunityResponseDTO.java, src/main/java/com/team9/anicare/community/mapper/CommunityMapper.java, src/main/java/com/team9/anicare/community/model/Comment.java, src/main/java/com/team9/anicare/community/model/CommunityLike.java, src/main/java/com/team9/anicare/community/service/CommentService.java, src/main/java/com/team9/anicare/community/service/CommunityService.java
커뮤니티 dto에서 필요 없는 정보는 삭제하고, user 정보를 추가했습니다.
- dto 필드 변경
=> refactor: dto에 필요한 user 정보 추가

src/main/java/com/team9/anicare/community/controller/CommunityController.java, src/main/java/com/team9/anicare/community/dto/AnimalSpeciesDTO.java, src/main/java/com/team9/anicare/community/repository/CommunityRepository.java, src/main/java/com/team9/anicare/community/service/CommunityService.java
카테고리 선택 시 선택할 수 있는 종 종류를 조회하는 api를 추가했습니다.
- AnimalSpeciesDTO 생성
- 종 종류 조회 api 추가
=> feat: 카테고리(종 종류) api 추가

src/main/java/com/team9/anicare/common/exception/ResultCode.java, src/main/java/com/team9/anicare/species/controller/SpeciesController.java, src/main/java/com/team9/anicare/species/dto/CreateAnimalDTO.java, src/main/java/com/team9/anicare/species/model/Breed.java, src/main/java/com/team9/anicare/species/repository/BreedRepository.java, src/main/java/com/team9/anicare/species/service/SpeciesService.java
품종에 관련한 entity, dto 등을 추가하였고, 종과 품종을 등록하는 api를 추가했습니다.
- 품종 entity, dto 추가
- 종 품종 등록 api 추가
- ResultCode 값 추가
=> feat: 품종 추가

src/main/java/com/team9/anicare/animal/controller/SpeciesController.java, src/main/java/com/team9/anicare/animal/dto/CreateAnimalDTO.java, src/main/java/com/team9/anicare/animal/model/Breed.java, src/main/java/com/team9/anicare/animal/model/Species.java, src/main/java/com/team9/anicare/animal/repository/BreedRepository.java, src/main/java/com/team9/anicare/animal/repository/SpeciesRepository.java, src/main/java/com/team9/anicare/animal/service/SpeciesService.java, src/main/java/com/team9/anicare/pet/service/PetService.java
기존 species 패키지에서 품종과 종을 추가하는 api를 구현해서 좀 더 포괄적인 이름으로 변경해봤습니다
=> chore : species 패키지 animal로 이름 변경

src/main/java/com/team9/anicare/animal/controller/AnimalController.java, src/main/java/com/team9/anicare/animal/dto/FindBreedDTO.java, src/main/java/com/team9/anicare/animal/dto/FindSpeciesDTO.java, src/main/java/com/team9/anicare/animal/repository/BreedRepository.java, src/main/java/com/team9/anicare/animal/service/AnimalService.java, src/main/java/com/team9/anicare/common/exception/ResultCode.java
=> feat : 종 조회, 품종 조회 api 구현

src/main/java/com/team9/anicare/pet/controller/PetController.java, src/main/java/com/team9/anicare/pet/dto/PetDTO.java, src/main/java/com/team9/anicare/pet/model/Pet.java, src/main/java/com/team9/anicare/pet/service/PetService.java
chore : Pet 엔터티에 breed 컬럼 추가
Pet 엔터티에 breed 컬럼 추가
service 코드 수정
=> chore : Pet 엔터티에 breed 컬럼 추가

src/main/java/com/team9/anicare/pet/controller/PetController.java, src/main/java/com/team9/anicare/pet/dto/PetDTO.java, src/main/java/com/team9/anicare/user/model/User.java
=> feat:User pet 권한 부여

src/main/java/com/team9/anicare/schedule/controller/SingleScheduleController.java
=> feat: user 권한부여

src/main/java/com/team9/anicare/animal/controller/AnimalController.java, src/main/java/com/team9/anicare/pet/controller/PetController.java, src/main/java/com/team9/anicare/schedule/controller/PeriodicScheduleController.java, src/main/java/com/team9/anicare/schedule/controller/SingleScheduleController.java, src/main/java/com/team9/anicare/schedule/model/PeriodicSchedule.java
swagger description 추가
swagger 설명 추가
=> feat : swagger description 추가

src/main/java/com/team9/anicare/schedule/dto/PeriodicScheduleDTO.java, src/main/java/com/team9/anicare/schedule/dto/SingleScheduleDTO.java, src/main/java/com/team9/anicare/schedule/service/PeriodicScheduleService.java, src/main/java/com/team9/anicare/schedule/service/SingleScheduleService.java
schedule,periodicSchedule DTO에 PetName 추가
schedule,periodicSchedule DTO에 PetName 추가
=> feat : schedule,periodicSchedule DTO에 PetName 추가

src/main/java/com/team9/anicare/community/controller/CommunityController.java, src/main/java/com/team9/anicare/community/dto/DetailResponseDTO.java, src/main/java/com/team9/anicare/community/repository/CommentRepository.java, src/main/java/com/team9/anicare/community/service/CommunityService.java
커뮤니티 게시글에 달리는 댓글에 대한 페이지네이션을 제거했습니다.
- CommentRepository 변경
=> refactor: 댓글 페이징 제거

src/main/java/com/team9/anicare/information/repository/InformationRepository.java, src/main/java/com/team9/anicare/information/service/InformationService.java
동물 정보 검색 시에 검색한 문자열이 포함된 품종을 검색하도록 수정했습니다
- InformationRepository 쿼리문 수정
=> refactor: 동물 정보 검색 수정

src/main/java/com/team9/anicare/hospital/controller/AnimalHospitalController.java, src/main/java/com/team9/anicare/hospital/dto/AnimalHospitalDto.java, src/main/java/com/team9/anicare/hospital/service/AnimalHospitalService.java
구, 동 바디값 변경 하지만 조만간 리팩토링 필요 발표이후 할듯
- 변경사항 1
- 변경사항 2
- 변경사항 3
=> fix: 동물병원 구, 동 바디값 변경 코드 리팩토링 나중에필요,,

src/main/java/com/team9/anicare/file/config/MultipartJackson2HttpMessageConverter.java, src/main/java/com/team9/anicare/schedule/controller/SingleScheduleController.java
swagger 파일 업로드 에러를 처리하는 클래스 추가
swagger 파일 업로드 에러를 처리하는 클래스 추가
=> feat : swagger 파일 업로드 에러를 처리하는 클래스 추가

src/main/java/com/team9/anicare/user/controller/UserController.java, src/main/java/com/team9/anicare/user/dto/UpdateUserDTO.java, src/main/java/com/team9/anicare/user/dto/UserDetailResponseDTO.java, src/main/java/com/team9/anicare/user/model/User.java, src/main/java/com/team9/anicare/user/service/UserService.java
user 업데이트 apit 추가하였습니다.
- 변경사항 1
- 변경사항 2
- 변경사항 3
=> feat: user업데이트 추가

src/main/java/com/team9/anicare/common/config/SwaggerConfig.java, src/main/java/com/team9/anicare/pet/controller/PetController.java
feat : swagger 토큰 구현
feat : swagger 토큰 구현
=> feat : swagger 토큰 구현

src/main/java/com/team9/anicare/hospital/controller/AnimalHospitalController.java
swagger 설명추가
- 변경사항 1
- 변경사항 2
- 변경사항 3
=> feat swagger 설명추가

src/main/java/com/team9/anicare/domain/animal/controller/AnimalController.java, src/main/java/com/team9/anicare/domain/auth/controller/AuthController.java, src/main/java/com/team9/anicare/domain/chat/controller/ChatController.java, src/main/java/com/team9/anicare/domain/chat/controller/ChatRoomController.java, src/main/java/com/team9/anicare/domain/hospital/controller/AnimalHospitalController.java, src/main/java/com/team9/anicare/domain/pet/controller/PetController.java, src/main/java/com/team9/anicare/domain/schedule/controller/PeriodicScheduleController.java, src/main/java/com/team9/anicare/domain/schedule/controller/SingleScheduleController.java, src/main/java/com/team9/anicare/domain/user/controller/UserController.java
=> refactor: swagger 설명 추가

src/main/java/com/team9/anicare/domain/pet/dto/PetDTO.java, src/main/java/com/team9/anicare/domain/pet/model/Pet.java, src/main/java/com/team9/anicare/domain/pet/service/PetService.java
@Setter 지우고 Builder패턴 적용
Pet 엔터티에 Builder패턴 적용
Service, DTO 수정
- [ O ] 관련 문서를 업데이트했나요?
=> refactor: Pet 엔터티에 Builder패턴 적용

src/main/java/com/team9/anicare/domain/community/model/Comment.java, src/main/java/com/team9/anicare/domain/community/model/Community.java, src/main/java/com/team9/anicare/domain/community/model/CommunityLike.java, src/main/java/com/team9/anicare/domain/community/service/CommentService.java, src/main/java/com/team9/anicare/domain/community/service/CommunityService.java, src/main/java/com/team9/anicare/domain/information/mapper/InformationMapper.java, src/main/java/com/team9/anicare/domain/information/model/Information.java, src/main/java/com/team9/anicare/domain/information/service/InformationService.java
Community, Information Entity에 @Setter를 제거하고 builder 패턴을 적용했습니다.
- 각 Entity에 @Setter 제거
- service에서 사용한 set 메소드 변경
=> refactor: builder 패턴 적용

src/main/java/com/team9/anicare/common/exception/ResultCode.java, src/main/java/com/team9/anicare/domain/community/controller/CommentController.java, src/main/java/com/team9/anicare/domain/community/dto/CommunityResponseDTO.java, src/main/java/com/team9/anicare/domain/community/model/Comment.java, src/main/java/com/team9/anicare/domain/community/model/CommunityLike.java, src/main/java/com/team9/anicare/domain/community/repository/CommunityLikeRepository.java, src/main/java/com/team9/anicare/domain/community/service/CommentService.java, src/main/java/com/team9/anicare/domain/community/service/CommunityService.java
좋아요 관련해서 필요한 필드랑 기능 추가했습니다.
- 좋아요 취소 API
- 커뮤니티 dto에 좋아요 상태 필드 추가
=> feat: 좋아요 기능

src/main/java/com/team9/anicare/domain/pet/dto/PetDTO.java, src/main/java/com/team9/anicare/domain/schedule/dto/SingleScheduleDTO.java, src/main/java/com/team9/anicare/domain/schedule/model/SingleSchedule.java, src/main/java/com/team9/anicare/domain/schedule/service/PeriodicScheduleService.java, src/main/java/com/team9/anicare/domain/schedule/service/SingleScheduleService.java
feat : builder적용, pet 전체조회 버그 수정
SingleSchedule에 builder적용
SingleScheduleService 수정
pet 전체조회 버그 수정
- [ O ] 관련 문서를 업데이트했나요?
=> feat : builder적용, pet 전체조회 버그 수정

src/main/java/com/team9/anicare/domain/schedule/model/PeriodicSchedule.java, src/main/java/com/team9/anicare/domain/schedule/service/PeriodicScheduleService.java
PeriodicSchedule에 builder적용
PeriodicSchedule에 builder적용
- [ O ] 관련 문서를 업데이트했나요?
=> feat: builder적용

src/main/java/com/team9/anicare/domain/pet/service/PetService.java
pet 전체 조회 builder 적용
pet 전체 조회 builder 적용
- [ O ] 관련 문서를 업데이트했나요?
=> feat: pet 전체 조회 builder 적용

src/main/java/com/team9/anicare/domain/schedule/dto/PeriodicScheduleDTO.java, src/main/java/com/team9/anicare/domain/schedule/service/PeriodicScheduleService.java
periodicSchedule builder 적용 수정
응답 DTO에 builder 적용
전체 조회에 builder 적용
=> feat: periodicSchedule builder 적용 수정

src/main/java/com/team9/anicare/domain/pet/dto/PetDTO.java
PetDTO 어노테이션 정리
- @Setter, @Builder삭제
=> feat: 어노테이션 정리

src/main/java/com/team9/anicare/domain/schedule/dto/SingleScheduleDTO.java
어노테이션 정리
- SingleScheduleDTO에 @Setter, @Builder 삭제
=> chore: 어노테이션 정리

src/main/java/com/team9/anicare/domain/animal/dto/FindBreedDTO.java, src/main/java/com/team9/anicare/domain/animal/dto/FindSpeciesDTO.java, src/main/java/com/team9/anicare/domain/animal/model/Breed.java, src/main/java/com/team9/anicare/domain/animal/model/Species.java, src/main/java/com/team9/anicare/domain/animal/service/AnimalService.java
animal에 builder 적용
-  animal에 builder 적용
=> refactor: builder 적용

src/main/java/com/team9/anicare/domain/auth/controller/AuthController.java, src/main/java/com/team9/anicare/domain/auth/service/KakaoService.java, src/main/java/com/team9/anicare/domain/user/dto/UserResponseDTO.java
=> Feat: role response 값 추가

src/main/java/com/team9/anicare/common/exception/GlobalExceptionHandler.java
채팅 예외처리 추가 앞으로도 더 추가예정 
- 변경사항 1
- 변경사항 2
- 변경사항 3
=> Feat: IllegalArgumentException 예외처리 추가

src/main/java/com/team9/anicare/domain/chat/controller/UserChatRoomController.java, src/main/java/com/team9/anicare/domain/chat/service/ChatRoomService.java
user가 자신이 만든 채팅방 조회할 때
전체 목록이 보이도록 list로 바꿨습니다
=> refactor: user 전체 채팅방 조회 list로 변경

src/main/java/com/team9/anicare/domain/chat/dto/ChatRoomResponseDTO.java, src/main/java/com/team9/anicare/domain/chat/service/ChatRoomService.java
채팅방 관련 응답에 채팅방 생성자 유저의 정보도 추가했습니다.
=> refactor: 채팅방 관련 응답에 user 정보 추가

src/main/java/com/team9/anicare/domain/chat/controller/AdminChatRoomController.java, src/main/java/com/team9/anicare/domain/chat/controller/UserChatRoomController.java, src/main/java/com/team9/anicare/domain/chat/dto/ChatMessageResponseDTO.java, src/main/java/com/team9/anicare/domain/chat/dto/ChatRoomResponseDTO.java, src/main/java/com/team9/anicare/domain/chat/repository/ChatRoomRepository.java, src/main/java/com/team9/anicare/domain/chat/service/ChatMessageService.java, src/main/java/com/team9/anicare/domain/chat/service/ChatRoomService.java
페이지네이션 누락된 부분 수정 및 경고 제거 용 단순 리팩터링
=> Feat chat 3 : 페이지네이션

src/main/java/com/team9/anicare/domain/chat/config/WebSocketEventListener.java, src/main/java/com/team9/anicare/domain/chat/controller/PingPongController.java, src/main/java/com/team9/anicare/domain/chat/dto/ChatRoomResponseDTO.java, src/main/java/com/team9/anicare/domain/chat/entity/ChatMessage.java, src/main/java/com/team9/anicare/domain/chat/service/ChatRoomService.java, src/main/java/com/team9/anicare/domain/chat/service/ChatServiceUtil.java, src/main/java/com/team9/anicare/domain/chat/service/UserSessionService.java, src/main/java/com/team9/anicare/domain/chat/service/UserStatusNotifier.java
활동 상태 메서드만 만들고 기능 구현 안 했던거 완성했습니다
=> Feat chat 4

src/main/java/com/team9/anicare/domain/chat/controller/AdminChatRoomController.java, src/main/java/com/team9/anicare/domain/chat/controller/UserChatRoomController.java, src/main/java/com/team9/anicare/domain/chat/repository/ChatRoomRepository.java, src/main/java/com/team9/anicare/domain/chat/service/ChatRoomService.java
한동님이 노션에 올려주신 방식으로 페이지네이션 방식 바꿨습니다.
common 패키지가 위에 따로 있는걸 못 봤네요 ㅠㅡㅠ
=> Feat chat 4 - 페이지네이션 구조 변경

src/socket-test.html
사용자 상태 업데이트도 잘 되는지 확인
(현활 / 오프라인)
=> Feat chat 6

src/main/java/com/team9/anicare/domain/pet/service/PetService.java
펫을 조회할떄 종이랑 종류가 null이나와서 추가해줬습니다.
- 종, 종류추가
=> Feat: 종, 종류 추가

src/main/java/com/team9/anicare/domain/schedule/service/PeriodicScheduleService.java
정기 일정의 마지막 주 스케줄 생성 버그 수정
-  요일로 날짜를 찾는 코드 수정
=> fix : 정기 일정의 마지막 주 스케줄 생성 버그 수정

src/create.html, src/main/java/com/team9/anicare/config/DataLoader.java, src/main/java/com/team9/anicare/domain/chat/controller/UserChatRoomController.java, src/main/java/com/team9/anicare/domain/chat/entity/ChatParticipant.java, src/main/java/com/team9/anicare/domain/chat/entity/ChatRoom.java, src/main/java/com/team9/anicare/domain/chat/service/ChatMessageService.java, src/main/java/com/team9/anicare/domain/chat/service/ChatRoomService.java, src/main/java/com/team9/anicare/domain/chat/service/ChatServiceUtil.java, src/main/java/com/team9/anicare/global/constants/ChatConstants.java, src/socket-test.html
사용자가 채팅방을 생성하고 검색하는 데에서 발생하는 자잘한 오류들 (시스템 메시지 처리 불가 등등) 수정
=> Feat chat 6 - 채팅방 생성 및 검색 수정 (user 쪽)

src/main/java/com/team9/anicare/domain/schedule/service/PeriodicScheduleService.java
정기 일정 요일에 대한 버그 수정
- 정기 일정 요일에 대한 버그 수정
=> fix: 정기 일정 버그 수정

src/main/java/com/team9/anicare/domain/schedule/controller/PeriodicScheduleController.java, src/main/java/com/team9/anicare/domain/schedule/controller/SingleScheduleController.java, src/main/java/com/team9/anicare/domain/schedule/service/PeriodicScheduleService.java, src/main/java/com/team9/anicare/domain/schedule/service/SingleScheduleService.java
delete요청에 @Requestparam -> @PathVariable로 변경
- @Requestparam -> @PathVariable로 변경
=> chore: @Requestparam -> @PathVariable로 변경

src/main/java/com/team9/anicare/domain/community/model/Community.java, src/main/java/com/team9/anicare/domain/user/controller/UserController.java, src/main/java/com/team9/anicare/domain/user/model/User.java
=> Chore: user 참조값 설정

src/main/java/com/team9/anicare/domain/auth/service/AuthService.java, src/main/java/com/team9/anicare/domain/user/service/UserService.java
=> Fix:user update 버그수정

src/main/java/com/team9/anicare/domain/pet/controller/PetController.java, src/main/java/com/team9/anicare/domain/pet/service/PetService.java
pet 상세 조회 api구현
- pet 상세 조회 구현
=> feat: pet 상세 조회 구현

src/main/java/com/team9/anicare/domain/chat/config/StompChannelInterceptor.java
=> fix: 메시지 전송 시 시큐리티 에러 해결

src/main/java/com/team9/anicare/domain/chat/config/StompChannelInterceptor.java
=> feat-chat-4

src/main/java/com/team9/anicare/domain/chat/controller/ChatController.java, src/main/java/com/team9/anicare/domain/chat/dto/ChatMessageResponseDTO.java
채팅 로그 조회 시 sender id도 함께 응답하도록 관련 내용 추가했습니다.
=> feat: 채팅 로그 조회 시 sender id도 함께 응답

src/main/java/com/team9/anicare/domain/chat/controller/ChatController.java
sender id 조회 수정했습니다.
name -> id 가져오는거로 변경 ,,ㅎㅎ
=> fix: sender id 조회 수정

src/main/java/com/team9/anicare/domain/chat/controller/ChatController.java, src/main/java/com/team9/anicare/domain/chat/service/ChatMessageService.java
sender 부분 builder로 수정 
- 변경사항 1
- 변경사항 2
- 변경사항 3
=> Fix: sender 부분 수정

src/main/java/com/team9/anicare/domain/schedule/controller/SingleScheduleController.java, src/main/java/com/team9/anicare/domain/schedule/service/MessageService.java
스케줄 카카오 알림 토큰 구현했습니다
- Controller에 uri 2개 추가
- MessageService.java 추가
=> feat: 스케줄 카카오 알림 토큰 구현

src/main/java/com/team9/anicare/domain/auth/client/KakaoClient.java, src/main/java/com/team9/anicare/domain/auth/controller/AuthController.java, src/main/java/com/team9/anicare/domain/auth/service/AuthService.java, src/main/java/com/team9/anicare/domain/auth/service/KakaoService.java
kakao auth 분리 했고 cookie함수도 만들었습니다.
=> Reafactor: kakao auth 분리, Cookie 함수

src/main/java/com/team9/anicare/domain/schedule/controller/SingleScheduleController.java, src/main/java/com/team9/anicare/domain/schedule/dto/MessageDTO.java, src/main/java/com/team9/anicare/domain/schedule/service/MessageService.java
=> feat: 메시지 요청 api 구현

src/main/java/com/team9/anicare/domain/chat/entity/ChatRoom.java
=> Fix:chatroom-cascade

src/main/java/com/team9/anicare/domain/schedule/service/MessageService.java
메세지 전송 메소드 리팩토링
- 메세지 전송 메소드 리팩토링
=> Refactor: 메세지 전송 메소드 리팩토링

src/main/java/com/team9/anicare/domain/auth/client/KakaoClient.java, src/main/java/com/team9/anicare/domain/auth/service/AuthService.java, src/main/java/com/team9/anicare/domain/auth/service/KakaoService.java, src/main/java/com/team9/anicare/domain/user/controller/UserController.java, src/main/java/com/team9/anicare/domain/user/model/User.java, src/main/java/com/team9/anicare/domain/user/service/UserService.java
=> Feat: 카카오소셜로그인 삭제

src/main/java/com/team9/anicare/domain/schedule/task/SchedulerTask.java
스케줄 알람 조회 시간 수정
- 1분에서 5분으로 수정
=> chore: 스케줄 알람 조회 시간 수정

src/main/java/com/team9/anicare/domain/chat/repository/ChatMessageRepository.java, src/main/java/com/team9/anicare/domain/chat/repository/ChatParticipantRepository.java, src/main/java/com/team9/anicare/domain/chat/repository/ChatRoomRepository.java, src/main/java/com/team9/anicare/domain/chat/service/ChatParticipantService.java, src/main/java/com/team9/anicare/domain/chat/service/ChatRoomService.java
- 채팅 수정
<br>
- 사용자가 나가면 채팅방 및 채팅 메시지 등등이 db에서 삭제됨
- 채팅방 생성 메시지 수정
=> fix: 사용자가 채팅방을 나가면 채팅방이 삭제되도록 수정

src/main/java/com/team9/anicare/domain/chat/controller/AdminChatRoomController.java, src/main/java/com/team9/anicare/domain/chat/repository/ChatMessageRepository.java, src/main/java/com/team9/anicare/domain/chat/repository/ChatParticipantRepository.java, src/main/java/com/team9/anicare/domain/chat/repository/ChatRoomRepository.java, src/main/java/com/team9/anicare/domain/chat/service/ChatRoomService.java
- 관리자 채팅방 목록 관련 수정
- 관리자에게도 자신이 참여한 채팅방 목록만 보이도록 수정
- 검색도 자신이 참여한 채팅방 안에서만 가능
- 채팅방이 하나도 없으면 빈 배열 응답 (관리자, 사용자 모두)
=> fix: 관리자 채팅방 목록 관련 수정

src/main/java/com/team9/anicare/domain/chat/controller/AdminChatRoomController.java, src/main/java/com/team9/anicare/domain/chat/repository/ChatMessageRepository.java, src/main/java/com/team9/anicare/domain/chat/repository/ChatParticipantRepository.java, src/main/java/com/team9/anicare/domain/chat/repository/ChatRoomRepository.java, src/main/java/com/team9/anicare/domain/chat/service/ChatRoomService.java
Reverts prgrms-be-devcourse/NBE2-3-2-team9#107
=> Revert "fix: 관리자 채팅방 목록 관련 수정"

src/main/java/com/team9/anicare/domain/information/repository/InformationRepository.java, src/main/java/com/team9/anicare/domain/information/service/InformationService.java
동물 정보 검색 시 품종만 입력해도 검색 가능하도록 수정
- getInformation()에 if문 추가
=> feat: 품종 검색 추가

src/main/java/com/team9/anicare/domain/information/controller/InformationController.java, src/main/java/com/team9/anicare/domain/information/model/Information.java, src/main/java/com/team9/anicare/domain/information/service/InformationService.java
=> feat: 동물 정보 수정/삭제

src/main/java/com/team9/anicare/domain/chat/service/ChatRoomService.java
=> Feat chat fix

build.gradle, src/main/java/com/team9/anicare/domain/chat/controller/AdminChatRoomController.java, src/main/java/com/team9/anicare/domain/chat/controller/UserChatRoomController.java, src/main/java/com/team9/anicare/domain/chat/dto/ChatRoomDetailResponseDTO.java, src/main/java/com/team9/anicare/domain/chat/service/ChatRoomService.java
채팅방 id로 방 제목과 설명 조회 기능 추가했습니다.
=> 채팅방 id로 방 제목과 설명 조회 기능 추가

src/main/java/com/team9/anicare/domain/chat/repository/ChatRoomRepository.java, src/main/java/com/team9/anicare/domain/chat/service/ChatRoomService.java
=> fix: 관리자 채팅 목록 쿼리 명시적으로 변경

src/main/java/com/team9/anicare/domain/chat/repository/ChatRoomRepository.java, src/main/java/com/team9/anicare/domain/chat/service/ChatRoomService.java
- 자기가 참여 중인 채팅방 잘 불러와지도록 수정했습니다.
=> fix: 관리자 채팅방 목록 수정

src/main/java/com/team9/anicare/domain/chat/controller/AdminChatRoomController.java, src/main/java/com/team9/anicare/domain/chat/controller/UserChatRoomController.java, src/main/java/com/team9/anicare/domain/chat/entity/ChatRoom.java, src/main/java/com/team9/anicare/domain/chat/service/ChatParticipantService.java, src/main/java/com/team9/anicare/domain/chat/service/ChatRoomService.java
- 관리자가 퇴장했을 때 db에서 지우는걸 빼먹어서 그 부분 추가했습니다
- 관리자나 사용자가 퇴장하면 db에서 삭제는 되는데, 응답 구조 때문에 에러가 발생해서 응답 구조 수정했습니다.
=> Feat chat fix v7
